### ISSUE TITLE
Please consider adding a license and a basic readme

### ISSUE THREAD

**Issue by sewera** [CloudCannon/humane#14]
That's a really nice testing tool! I've come across it while deep diving into the build process of https://github.com/CloudCannon/pagefind — I must say, really professionally-engineered piece of software.

I really like that this project is source-available, but there's no way to use it legally. Please consider adding a license and some basic readme if you're inclined to :)

**Comment by bglw** [comment]
Hey @sewera 👋 Thanks for the kind words!

I have added a license file (MIT), and also added a readme — though with some noted caveats. Pinned versions are fine to use, as long as you're comfortable with significant changes happening in future releases — this tool is still in a state of flux as we shape it to fit our needs 🙂
